language: python
sudo: false
cache: pip

python:
  - "3.5"

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" MAKEPOT="0"
  # Set this variable to some version existing as linux-generic build on
  # https://github.com/wkhtmltopdf/wkhtmltopdf/releases
  # if you need to install wkhtmltopdf
  # - WKHTMLTOPDF_VERSION="0.12.5"
  # Set the above to install a `wkhtmltopdf` version that is not the one provided
  # by the `pov-wkhtmltopdf` repo.
  - PHANTOMJS_VERSION="latest"
  # The above line controls the PhantomJS version that is used for JS testing.
  #   It is not necessary to include this value unless you are altering the default.
  #   Use `OS` to skip the PhantomJS upgrade & use the system version instead.
  - WEBSITE_REPO="1"
  # Use the above line to install dependencies that are required for website repos:
  # * SASS & Bootstrap-SASS
  # * Compass

  matrix:
  - LINT_CHECK="1"
# use this to install a standalone database to export .pot files
# - MAKEPOT="1"
# add MAKEPOT="1" to a TEST line to export .pot files from
# the test database after test success
  - TESTS="1" ODOO_REPO="odoo/odoo" MAKEPOT="1"
  - TESTS="1" ODOO_REPO="OCA/OCB"

install:
  - git clone --depth=1 https://github.com/odoo/odoo.git ${HOME}/kojo-motors-project
  - export PATH=${HOME}/kojo-motors-project/travis:${PATH}
  -

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success